/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Examen.Final.BDMuseo.vista;

/**
 *
 * @author Paula
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JButtonObra = new javax.swing.JButton();
        jButtonMuseo = new javax.swing.JButton();
        jButtonExposicion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("POR FAVOR PRESIONE EL BOTON DE LA TABLA QUE DESEA HACER CRUD");

        JButtonObra.setText("OBRA");
        JButtonObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonObraActionPerformed(evt);
            }
        });

        jButtonMuseo.setText("MUSEO");
        jButtonMuseo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMuseoActionPerformed(evt);
            }
        });

        jButtonExposicion.setText("EXPOSICION");
        jButtonExposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExposicionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JButtonObra, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jButtonMuseo)
                        .addGap(79, 79, 79)
                        .addComponent(jButtonExposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 92, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonObra, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMuseo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonObraActionPerformed
        ventana1();
    }//GEN-LAST:event_JButtonObraActionPerformed

    private void jButtonExposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExposicionActionPerformed
        ventana3();
    }//GEN-LAST:event_jButtonExposicionActionPerformed

    private void jButtonMuseoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMuseoActionPerformed
        ventana2();
    }//GEN-LAST:event_jButtonMuseoActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonObra;
    private javax.swing.JButton jButtonExposicion;
    private javax.swing.JButton jButtonMuseo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void ventana1() {
        VentanaObra ventana=new VentanaObra();
        ventana.setTitle("Obra");
        ventana.setVisible(true);
    }

    private void ventana2() {
        VentanaMuseo ventana=new VentanaMuseo();
        ventana.setTitle("Museo");
        ventana.setVisible(true);
    }

    private void ventana3() {
        VentanaExposicion ventana=new VentanaExposicion();
        ventana.setTitle("Exposicion");
        ventana.setVisible(true);
    }
}
