/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Examen.Final.BDMuseo.vista;

import java.util.Optional;
import Examen.Final.BDMuseo.BDMuseoApplication;
import Examen.Final.BDMuseo.SpringContext;
import Examen.Final.BDMuseo.modelos.Exposicion;
import Examen.Final.BDMuseo.repositorios.ExposicionRepositorio;

/**
 *
 * @author Paula
 */
public class VentanaExposicion extends javax.swing.JFrame {
    
    ExposicionRepositorio exposicionRepositorio;
    
    /**
     * Creates new form VentanaExposicion
     */
    public VentanaExposicion() {
        initComponents();
        
        String [] args = {};
        BDMuseoApplication.runSpringServer(args);
        
        exposicionRepositorio=SpringContext.getBean(ExposicionRepositorio.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btCrear = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btGuardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lbNotificaciones = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btEliminar = new javax.swing.JButton();
        tfNombre = new javax.swing.JTextField();
        btLimpiar = new javax.swing.JButton();
        tfId = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        tfMusId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("id");

        btCrear.setText("Crear");
        btCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearActionPerformed(evt);
            }
        });

        btConsultar.setText("Consultar expo por id");
        btConsultar.setActionCommand("");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre Exposicion");

        btEliminar.setText("Eliminar");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });

        btLimpiar.setText("Limpiar");
        btLimpiar.setToolTipText("");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        tfId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel5.setText("Mus_Id");
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btGuardar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfMusId)
                                    .addComponent(tfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(51, 51, 51)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLimpiar)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lbNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btConsultar)
                    .addComponent(btCrear)
                    .addComponent(btEliminar)
                    .addComponent(btLimpiar)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfMusId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(lbNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearActionPerformed
        limpiarCamposParaCreacion();
    }//GEN-LAST:event_btCrearActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        if(!tfId.getText().equals("")){
            buscarPorId();
            tfId.setEnabled(true);
        }
        else{
            lbNotificaciones.setText("No ha digitado ningun id");
        }
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        crear();
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
        if(!tfId.getText().equals("")){
            eliminar();
        }
    }//GEN-LAST:event_btEliminarActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btLimpiarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btCrear;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbNotificaciones;
    private javax.swing.JFormattedTextField tfId;
    private javax.swing.JTextField tfMusId;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables

    public void limpiarCamposParaCreacion(){
        btCrear.setEnabled(false);
        tfNombre.setText("");
        tfMusId.setText("");
        tfId.setText("");
        lbNotificaciones.setText("");
    }
    
    public void limpiarCampos(){
        btCrear.setEnabled(true);
        tfNombre.setText("");
        tfMusId.setText("");
        tfId.setText("");
        lbNotificaciones.setText("");
    }
    
    private void buscarPorId() {
        
        Long id = Long.parseLong(tfId.getText());
        Optional<Exposicion> optionalExposicion = exposicionRepositorio.findById(id);
        if(optionalExposicion.isPresent()){
            Exposicion exposicion = optionalExposicion.get();
            tfNombre.setText(exposicion.getExpNombre());
            tfMusId.setText(exposicion.getMusId().toString());
            
            lbNotificaciones.setText(
                    "La Exposicion que ud busca es: " + tfNombre.getText());
        }
        else{
            // Error cuando no existe el id
            lbNotificaciones.setText(
                    "La exposicion con id: " + tfId.getText() + 
                            " no existe en la base de datos");
        }
    }

    private Exposicion obtenerDatosDeFormulario(){
        Exposicion exposicion = new Exposicion();
        exposicion.setExpId(Long.parseLong(tfId.getText()));
        exposicion.setExpNombre(tfNombre.getText());
        exposicion.setMusId(Long.parseLong(tfMusId.getText()));
        return exposicion;
    }
    
    private void crear() {
        Exposicion exposicion = obtenerDatosDeFormulario();
        
        Long id = Long.parseLong(tfId.getText());
        Optional<Exposicion> optionalExposicion = exposicionRepositorio.findById(id);
        StringBuffer respuesta = new StringBuffer();
        if(optionalExposicion.isPresent()){
            respuesta.append("Se actualizó la exposicion: ");
        }
        else{
            respuesta.append("Se creó la exposicion: ");
        }
        exposicion.setExpId(id);
                
        try{
            exposicionRepositorio.save(exposicion); // Grabeme la obra obtenida del formulario
            respuesta.append(exposicion.getExpNombre()); //
            tfId.setText(exposicion.getExpId().toString());
            lbNotificaciones.setText(respuesta.toString());
        }
        catch(Exception e)
        {
            lbNotificaciones.setText("Ocurrio un error al guardar");
        }
       
    }
   
    public void eliminar(){
        Long id = Long.parseLong(tfId.getText());
        
        try{
            exposicionRepositorio.deleteById(id);
            lbNotificaciones.setText("Se eliminó la exposicion con id: " + id.toString());
        }
        catch(Exception e)
        {
            lbNotificaciones.setText("Ocurrio un error al eliminar");
        }
                
    }
}
